// Code generated by 'yaegi extract slices'. DO NOT EDIT.

//go:build go1.24
// +build go1.24

package stdlib

import (
	"reflect"
)

func init() {
	Symbols["slices/slices"] = map[string]reflect.Value{}
}
